-- Enable REPLICA IDENTITY FULL for all tables (idempotent)
ALTER TABLE public.trips REPLICA IDENTITY FULL;
ALTER TABLE public.parcels REPLICA IDENTITY FULL;
ALTER TABLE public.profiles REPLICA IDENTITY FULL;
ALTER TABLE public.reviews REPLICA IDENTITY FULL;
ALTER TABLE public.messages REPLICA IDENTITY FULL;
ALTER TABLE public.flags REPLICA IDENTITY FULL;
ALTER TABLE public.threads REPLICA IDENTITY FULL;